### ISSUE TITLE
Create version for QGIS 3

### ISSUE THREAD

**Issue by pedrocamargo** [pedrocamargo/rasterstats#4]
Upgrade the plugin to work with QGIS 3

**Comment by hkristen** [comment]
Any progress on this? Would be much appreciated :)

**Comment by pedrocamargo** [comment]
Zero progress.   I have a lot on my plate and, to be honest, this is not one of the priorities. Since it is quite simple to migrate, I might do it sooner rather than later, but no promises.

**Comment by hkristen** [comment]
Okidoki ... thanks for the info :) I will solve the problem with python-rasterstats & jupyter then!

**Comment by pedrocamargo** [comment]
Done!
